### ISSUE TITLE
Assertions not matching randomly

### ISSUE THREAD

**Issue by acostacos** [gambitph/Stackable-e2e-tests#123]
- ex. Font size expected to be 50px but found 5px
- Speculated that it might be happening due to animations when adjusting
- Asserts when the element has not yet fully adjusted to style change
- Suggestion: try removing all transitions from the beginning

ex.
`
.editor-styles-wrapper .wp-block, .editor-styles-wrapper .wp-block * { Transform: none !important; }
`

**Comment by blankart** [comment]
This should be `transition: none !important` instead of `transform`
