### ISSUE TITLE
Single column tests for columns block fails

### ISSUE THREAD

**Issue by acostacos** [gambitph/Stackable-e2e-tests#124]
- Happens in columns.spec.js
- Due to single column tests not implementing registerBlockSnapshots
- registerBlockSnapshots overwrites the assert commands

![image](https://user-images.githubusercontent.com/33932255/111773332-022a0d80-88e9-11eb-956a-d8fad5b5d438.png)

**Comment by blankart** [comment]
Creating a new spec file for column would temporarily fix the issue. We need to rethink how to handle static blocks (block snapshots)
