### ISSUE TITLE
cy.click error for Windows

### ISSUE THREAD

**Issue by acostacos** [gambitph/Stackable-e2e-tests#126]
- Observed that this behavior only happens on Windows machines
- Happens when using assert

![Windows error](https://user-images.githubusercontent.com/33932255/111774175-14f11200-88ea-11eb-81b4-1a9605abcaff.PNG)

**Comment by legaspielaine** [comment]
Fixed by https://github.com/gambitph/Stackable-e2e-tests/pull/129
