### ISSUE TITLE
Refactor `cy.addBlock` to append the e2e className

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable-e2e-tests#227]
We need to refactor `cy.addBlock` to only append the className (and not overwrite) when adding blocks since in version 3, there are default values added in CSS classes such as:

<img width="314" alt="Screen Shot 2021-09-01 at 12 10 49 PM" src="https://user-images.githubusercontent.com/28699204/131610467-85d14715-c0bd-4600-890c-c036796a0c75.png">

**Comment by blankart** [comment]
We can easily address this by only matching the e2e generated classnames using regexp
